### ISSUE TITLE
100x faster inverse modulo.

### ISSUE THREAD

**Issue by Sjors** [CryptoCoinSwift/UInt256#3]
The function [modInverse](https://github.com/CryptoCoinSwift/UInt256/blob/master/Classes/UInt256%2BIntegerArithmetic.swift#L129) is much too slow. It takes 21 milliseconds on a Macbook Pro to calculate the modular inverse of a 256 bit integer, compared to 0.2 in Ruby. The relevant performance test for this is [testModularMultiplicativeInverse](https://github.com/CryptoCoinSwift/UInt256/blob/master/UInt256Tests/UInt256TestArithmetic.swift#L371). 

I'd like to solve this without using an external math library. I also prefer a solution that keeps the existing swift abstractions to a solution that just falls back to C. But as long as it works on iOs and Mac, that's a great start.

See also #2.

**Comment by ronyfadel** [comment]
I would close the bounty as it brings unneeded attention: the project is out of date, and uses an unsupported version of Swift (2.x). Hunting for the bounty would be impractical before a project overhaul.

**Comment by Sjors** [comment]
@ronyfadel unfortunately there's no way to close bounties afaik.

**Comment by Sjors** [comment]
I'll just close the issue.

**Comment by ronyfadel** [comment]
Thanks!
